# Generated by Django 5.0.2 on 2024-02-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_column="username",
                        max_length=50,
                        null=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_column="phone",
                        max_length=11,
                        null=True,
                        verbose_name="phone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_column="email",
                        max_length=254,
                        null=True,
                        verbose_name="email",
                    ),
                ),
            ],
        ),
    ]
