# Generated by Django 5.0.2 on 2024-02-12 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crudApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="person",
            table="Persons",
        ),
    ]
